# Generated by Django 5.2.15 on 2026-06-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadinessPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_summary", models.TextField()),
                ("competencies", models.JSONField(blank=True, default=list)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("gaps", models.JSONField(blank=True, default=list)),
                ("evidence_completeness", models.JSONField(blank=True, default=dict)),
                ("story_coverage", models.JSONField(blank=True, default=dict)),
                ("matched_story_excerpt", models.JSONField(blank=True, default=dict)),
                ("prepkit_explanation", models.TextField()),
                ("input_revision", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_previews",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "status"],
                        name="previews_re_sprint__f8ffbd_idx",
                    ),
                    models.Index(
                        fields=["sprint", "input_revision"],
                        name="previews_re_sprint__8d807b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["DRAFT", "READY"])),
                        fields=("sprint", "input_revision"),
                        name="one_current_preview_per_sprint_revision",
                    )
                ],
            },
        ),
    ]
