# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("current_role", models.CharField(blank=True, max_length=255, null=True)),
                ("current_company", models.CharField(blank=True, max_length=255, null=True)),
                ("years_experience", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("industries", models.JSONField(blank=True, default=list)),
                ("functional_areas", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("education_summary", models.TextField(blank=True, null=True)),
                ("career_summary", models.TextField(blank=True, null=True)),
                ("positioning_summary", models.TextField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_profiles",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "confirmation_status"],
                        name="profiles_ca_user_id_8b20e6_idx",
                    ),
                    models.Index(
                        fields=["user", "active_resume"],
                        name="profiles_ca_user_id_35099d_idx",
                    ),
                ],
            },
        ),
    ]
