# Generated by Codex on 2026-06-13

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerprofile",
            name="ai_attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="careerprofile",
            name="extraction_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="careerprofile",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_STARTED",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="careerprofile",
            constraint=models.UniqueConstraint(
                condition=~Q(confirmation_status="STALE"),
                fields=("user", "active_resume"),
                name="one_current_profile_per_resume",
            ),
        ),
    ]
