# Generated by Django 5.2.15 on 2026-06-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_title", models.CharField(max_length=255)),
                (
                    "role_family",
                    models.CharField(
                        choices=[
                            ("PRODUCT_MANAGEMENT", "Product Management"),
                            ("AI_PRODUCT_MANAGEMENT", "AI Product Management"),
                            ("SOFTWARE_ENGINEERING", "Software Engineering"),
                            ("DATA_ANALYTICS", "Data and Analytics"),
                            (
                                "SALES_BUSINESS_DEVELOPMENT",
                                "Sales and Business Development",
                            ),
                            ("CONSULTING_STRATEGY_OPS", "Consulting/Strategy/Ops"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("target_seniority", models.CharField(max_length=128)),
                ("company_name", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("interview_stage", models.CharField(blank=True, max_length=128)),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("concerns", models.TextField(blank=True)),
                ("improvement_goals", models.TextField(blank=True)),
                ("jd_analysis", models.JSONField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "confirmation_status"],
                        name="opportuniti_sprint__c8210b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("confirmation_status", "STALE"), _negated=True),
                        fields=("sprint",),
                        name="one_current_opportunity_per_sprint",
                    )
                ],
            },
        ),
    ]
