# Generated by Django 5.2.15 on 2026-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="company_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="company_context_status",
            field=models.CharField(
                choices=[
                    ("NOT_PROVIDED", "Not provided"),
                    ("PENDING_REVIEW", "Pending review"),
                    ("CONFIRMED", "Confirmed"),
                    ("SKIPPED", "Skipped"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="NOT_PROVIDED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="company_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
