# Generated by Django 5.2.15 on 2026-06-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("profiles", "0002_profile_extraction_status_and_idempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("metric", models.CharField(blank=True, max_length=255, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("source_note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_highlights",
                        to="profiles.careerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("problem", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("action", models.TextField(blank=True, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("metric", models.CharField(blank=True, max_length=255, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("competencies", models.JSONField(blank=True, default=list)),
                ("ownership_signal", models.TextField(blank=True, null=True)),
                ("constraints", models.TextField(blank=True, null=True)),
                ("tradeoffs", models.TextField(blank=True, null=True)),
                ("missing_details", models.JSONField(blank=True, default=list)),
                ("source_excerpt", models.TextField()),
                ("source_location", models.CharField(blank=True, max_length=255)),
                ("confidentiality", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("NEEDS_DETAIL", "Needs detail"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("duplicate_reason", models.TextField(blank=True)),
                ("ai_generated_data", models.JSONField(blank=True, default=dict)),
                ("user_edited_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_suggestions",
                        to="evidence.evidencecard",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_cards",
                        to="profiles.careerprofile",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_cards",
                        to="documents.document",
                    ),
                ),
                (
                    "source_highlight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_cards",
                        to="evidence.careerhighlight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="careerhighlight",
            index=models.Index(
                fields=["user", "profile", "status"],
                name="evidence_ca_user_id_78a696_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencecard",
            index=models.Index(
                fields=["user", "profile", "status"],
                name="evidence_ev_user_id_ad2455_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencecard",
            index=models.Index(fields=["profile", "status"], name="evidence_ev_profile_dc105f_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencecard",
            index=models.Index(fields=["source_document"], name="evidence_ev_source__ac874d_idx"),
        ),
        migrations.AddIndex(
            model_name="evidencecard",
            index=models.Index(fields=["source_highlight"], name="evidence_ev_source__8845e4_idx"),
        ),
    ]
