# Generated by Django 5.2.15 on 2026-06-16 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("GENERATE_PREVIEW", "Generate readiness preview")],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("input_revision", models.CharField(db_index=True, max_length=128)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_runs",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="generations_status_21495b_idx",
                    ),
                    models.Index(
                        fields=["sprint", "operation", "status"],
                        name="generations_sprint__818e73_idx",
                    ),
                    models.Index(
                        fields=["sprint", "operation", "input_revision"],
                        name="generations_sprint__323968_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                        fields=("sprint", "operation", "input_revision"),
                        name="one_active_generation_run_per_revision",
                    )
                ],
            },
        ),
    ]
