# Generated by Django 5.2.15 on 2026-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationrun",
            name="operation",
            field=models.CharField(
                choices=[
                    ("GENERATE_PREVIEW", "Generate readiness preview"),
                    ("GENERATE_PREPKIT", "Generate paid Prep Kit"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
