# Generated by Django 5.2.15 on 2026-06-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_profile_extraction_status_and_idempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("story_type", models.CharField(blank=True, max_length=64)),
                ("situation", models.TextField(blank=True, null=True)),
                ("task", models.TextField(blank=True, null=True)),
                ("action", models.TextField(blank=True, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("learning", models.TextField(blank=True, null=True)),
                ("short_answer", models.TextField()),
                ("ninety_second_answer", models.TextField()),
                ("detailed_answer", models.TextField()),
                ("competency_tags", models.JSONField(blank=True, default=list)),
                ("seniority_signals", models.JSONField(blank=True, default=list)),
                ("evidence_ids", models.JSONField(blank=True, default=list)),
                (
                    "specificity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "impact_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ownership_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "clarity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("missing_details", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("EDITED", "Edited"),
                            ("STALE", "Stale"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("revision_number", models.PositiveSmallIntegerField(default=1)),
                ("ai_generated_data", models.JSONField(blank=True, default=dict)),
                ("user_edited_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="profiles.careerprofile",
                    ),
                ),
                (
                    "source_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="stories.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "profile", "status"],
                        name="stories_sto_user_id_87d664_idx",
                    ),
                    models.Index(
                        fields=["profile", "status"],
                        name="stories_sto_profile_ff5859_idx",
                    ),
                    models.Index(
                        fields=["source_story"], name="stories_sto_source__e1de54_idx"
                    ),
                ],
            },
        ),
    ]
