# Generated by Django 5.2.15 for Stage 1A.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RESUME_READY", "Resume ready"),
                            ("PROFILE_CONFIRMED", "Profile confirmed"),
                            ("OPPORTUNITY_CONFIRMED", "Opportunity confirmed"),
                            ("EVIDENCE_REVIEW", "Evidence review"),
                            ("EVIDENCE_APPROVED", "Evidence approved"),
                            ("STORIES_READY", "Stories ready"),
                            ("MATCHING_READY", "Matching ready"),
                            ("PREVIEW_READY", "Preview ready"),
                            ("PAYMENT_PENDING", "Payment pending"),
                            ("PAID", "Paid"),
                            ("PREPKIT_READY", "Prep Kit ready"),
                            ("PRACTICE_ACTIVE", "Practice active"),
                            ("PLAN_READY", "Plan ready"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="interviewsprint",
            index=models.Index(fields=["user", "state"], name="sprints_int_user_id_83429d_idx"),
        ),
    ]
