# Generated by Django 5.2.15 on 2026-06-13 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interviewsprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "COMPLETED"), _negated=True),
                fields=("user",),
                name="one_current_interview_sprint_per_user",
            ),
        ),
    ]
