# Generated by Django 5.2.15 on 2026-06-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("sprints", "0002_interviewsprint_one_current_interview_sprint_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsprint",
            name="active_resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_sprints",
                to="documents.document",
            ),
        ),
    ]
