# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("sprints", "0003_interviewsprint_active_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsprint",
            name="active_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_sprints",
                to="profiles.careerprofile",
            ),
        ),
    ]
