# Generated by Django 5.2.15 on 2026-06-13 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("RESUME", "Resume")],
                        db_index=True,
                        default="RESUME",
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("cleaned_text", models.TextField(blank=True)),
                (
                    "parsing_status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATING", "Validating"),
                            ("PARSING", "Parsing"),
                            ("READY_FOR_REVIEW", "Ready for review"),
                            ("CONFIRMED", "Confirmed"),
                            ("INVALID_FILE", "Invalid file"),
                            ("PARSING_FAILED", "Parsing failed"),
                            ("REPLACED", "Replaced"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=32,
                    ),
                ),
                ("parsing_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "document_type", "is_active"],
                        name="documents_d_user_id_01e3d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("document_type", "RESUME"), ("is_active", True)
                        ),
                        fields=("user",),
                        name="one_active_resume_document_per_user",
                    )
                ],
            },
        ),
    ]
