# Generated by Django 5.2.15 on 2026-06-16 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="razorpay", max_length=32),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("ORDER_CREATED", "Order created"),
                            ("PAYMENT_PENDING", "Payment pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=32,
                    ),
                ),
                (
                    "webhook_event_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sprints.interviewsprint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
                    ),
                    models.Index(
                        fields=["sprint", "status"],
                        name="payments_pa_sprint__25183f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_order_id", ""), _negated=True),
                        fields=("sprint", "provider", "provider_order_id"),
                        name="unique_payment_order_per_sprint",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("provider_payment_id", ""), _negated=True),
                        fields=("provider", "provider_payment_id"),
                        name="unique_provider_payment_id",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PAID")),
                        fields=("sprint",),
                        name="one_paid_payment_per_sprint",
                    ),
                ],
            },
        ),
    ]
