# Generated by Django 5.2.15 on 2026-06-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
        ("stories", "0002_storygenerationfailure"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competency_key", models.CharField(db_index=True, max_length=128)),
                ("competency_label", models.CharField(blank=True, max_length=255)),
                ("competency_score", models.PositiveSmallIntegerField(default=0)),
                ("role_relevance_score", models.PositiveSmallIntegerField(default=0)),
                ("seniority_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "evidence_strength_score",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("company_context_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("explanation", models.TextField(blank=True)),
                ("jd_excerpt", models.TextField(blank=True)),
                ("evidence_ids", models.JSONField(blank=True, default=list)),
                ("missing_signal", models.TextField(blank=True)),
                ("recommended_emphasis", models.TextField(blank=True)),
                ("user_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alternative_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alternative_matches",
                        to="stories.story",
                    ),
                ),
                (
                    "primary_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_matches",
                        to="stories.story",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_matches",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["competency_key", "-total_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "competency_key"],
                        name="matching_st_sprint__a7b6c8_idx",
                    ),
                    models.Index(
                        fields=["sprint", "user_selected"],
                        name="matching_st_sprint__fd3460_idx",
                    ),
                    models.Index(
                        fields=["sprint", "total_score"],
                        name="matching_st_sprint__e666fc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sprint", "competency_key"),
                        name="one_story_match_per_sprint_competency",
                    )
                ],
            },
        ),
    ]
