# Generated by Django 5.2.15 on 2026-06-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
        ("stories", "0002_storygenerationfailure"),
    ]

    operations = [
        migrations.AddField(
            model_name="storymatch",
            name="selected_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_matches",
                to="stories.story",
            ),
        ),
    ]
