# Generated by Django 5.2.15 on 2026-06-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
        ("stories", "0002_storygenerationfailure"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(db_index=True, max_length=128)),
                ("answer_text", models.TextField()),
                ("relevance_score", models.PositiveSmallIntegerField()),
                ("structure_score", models.PositiveSmallIntegerField()),
                ("specificity_score", models.PositiveSmallIntegerField()),
                ("ownership_score", models.PositiveSmallIntegerField()),
                ("impact_score", models.PositiveSmallIntegerField()),
                ("clarity_score", models.PositiveSmallIntegerField()),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("improved_answer", models.TextField()),
                ("follow_up_question", models.TextField()),
                ("attempt_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_attempts",
                        to="stories.story",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "question_id", "-created_at"],
                        name="practice_pr_sprint__2b1335_idx",
                    ),
                    models.Index(
                        fields=["sprint", "-created_at"],
                        name="practice_pr_sprint__c2b3f4_idx",
                    ),
                    models.Index(
                        fields=["linked_story"], name="practice_pr_linked__fb9150_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sprint", "question_id", "attempt_number"),
                        name="one_practice_attempt_number_per_question",
                    )
                ],
            },
        ),
    ]
