# Generated by Django 5.2.15 on 2026-06-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evidence", "0001_initial"),
        ("sprints", "0004_interviewsprint_active_profile"),
        ("stories", "0002_storygenerationfailure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImprovementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("plan_length_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "generated_from_revision",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_plans",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("EVIDENCE_GAP", "Evidence gap"),
                            ("STORY_IMPROVEMENT", "Story improvement"),
                            ("MATCH_GAP", "Match gap"),
                            ("PRACTICE", "Practice"),
                            ("COMPANY_RESEARCH", "Company research"),
                            ("USER_GOAL", "User goal"),
                            ("FINAL_REVIEW", "Final review"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("instructions", models.TextField()),
                ("estimated_minutes", models.PositiveSmallIntegerField()),
                ("linked_question_id", models.CharField(blank=True, max_length=128)),
                ("priority", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "Todo"),
                            ("DONE", "Done"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="TODO",
                        max_length=32,
                    ),
                ),
                ("task_fingerprint", models.CharField(db_index=True, max_length=128)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to="evidence.evidencecard",
                    ),
                ),
                (
                    "linked_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to="stories.story",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="plans.improvementplan",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "-priority", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="improvementplan",
            index=models.Index(fields=["sprint", "status"], name="plans_impro_sprint__b2d18c_idx"),
        ),
        migrations.AddIndex(
            model_name="improvementplan",
            index=models.Index(
                fields=["sprint", "generated_from_revision"],
                name="plans_impro_sprint__683993_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="improvementplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["DRAFT", "ACTIVE"])),
                fields=("sprint",),
                name="one_current_improvement_plan_per_sprint",
            ),
        ),
        migrations.AddIndex(
            model_name="plantask",
            index=models.Index(
                fields=["plan", "day_number"], name="plans_plant_plan_id_9b96a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plantask",
            index=models.Index(fields=["plan", "status"], name="plans_plant_plan_id_2f3cdf_idx"),
        ),
        migrations.AddIndex(
            model_name="plantask",
            index=models.Index(fields=["linked_evidence"], name="plans_plant_linked__4efef3_idx"),
        ),
        migrations.AddIndex(
            model_name="plantask",
            index=models.Index(fields=["linked_story"], name="plans_plant_linked__2a386d_idx"),
        ),
        migrations.AddConstraint(
            model_name="plantask",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_number__gte", 1), ("day_number__lte", 7)),
                name="plan_task_day_between_1_and_7",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantask",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_minutes__gte", 5), ("estimated_minutes__lte", 45)),
                name="plan_task_estimated_minutes_between_5_and_45",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantask",
            constraint=models.UniqueConstraint(
                fields=("plan", "task_fingerprint"),
                name="one_plan_task_per_fingerprint",
            ),
        ),
    ]
