# Generated by Django 5.2.15 on 2026-06-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0004_interviewsprint_active_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("STALE", "Stale"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("role_briefing", models.JSONField(blank=True, default=dict)),
                ("fit_summary", models.JSONField(blank=True, default=dict)),
                ("competency_coverage", models.JSONField(blank=True, default=list)),
                ("story_map", models.JSONField(blank=True, default=list)),
                ("question_bank", models.JSONField(blank=True, default=list)),
                ("concern_map", models.JSONField(blank=True, default=list)),
                ("missing_evidence", models.JSONField(blank=True, default=list)),
                ("practice_priorities", models.JSONField(blank=True, default=list)),
                ("seven_day_plan", models.JSONField(blank=True, default=list)),
                ("interview_checklist", models.JSONField(blank=True, default=list)),
                ("input_revision", models.CharField(db_index=True, max_length=128)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_kits",
                        to="sprints.interviewsprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "status"],
                        name="prepkits_pr_sprint__05be17_idx",
                    ),
                    models.Index(
                        fields=["sprint", "input_revision"],
                        name="prepkits_pr_sprint__85739b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "READY"])),
                        fields=("sprint", "input_revision"),
                        name="one_current_prepkit_per_sprint_revision",
                    )
                ],
            },
        ),
    ]
